version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - upsign-network

  api:
    build: ./api
    ports:
      - '3001:3002'
    environment:
      - DATABASE_URL=postgresql://johndoe:randompassword@postgres:5432/mydb?schema=public
      - JWT_SECRET=your-secret-key
      - PORT=3002
    depends_on:
      - postgres
    networks:
      - upsign-network

  app:
    build: ./app
    ports:
      - '3000:3000'
    environment:
      - JWT_SECRET=your-secret-key
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - api
    networks:
      - upsign-network

volumes:
  postgres_data:

networks:
  upsign-network:
    driver: bridge
